;; Gramps key file
;; Automatically created at 2026/04/01 13:08:20

[behavior]
;;addmedia-image-dir=''
;;addmedia-relative-path=0
addons-allow-install=1
;;addons-projects=[['Gramps', 'https://raw.githubusercontent.com/gramps-project/addons/master/gramps60', True]]
;;addons-url='https://raw.githubusercontent.com/gramps-project/addons/master/gramps60'
autoload=1
;;avg-generation-gap=20
check-for-addon-update-types=['update', 'new']
check-for-addon-updates=2
;;date-about-range=50
;;date-after-range=50
;;date-before-range=50
;;do-not-show-previously-seen-addon-updates=1
;;generation-depth=15
;;immediate-warn=0
last-check-for-addon-updates='2026/03/23'
;;max-age-prob-alive=110
;;max-sib-age-diff=20
;;min-generation-years=13
;;owner-warn=0
;;pop-plugin-status=0
previously-seen-addon-updates=['AncestorFill', 'DescendantBook', 'DetailedDescendantBook', 'DynamicWeb', 'Heatmap', 'LinesOfDescendency', 'ListeEclair', 'MediaReport', 'PersonEverythingReport', 'TimePedigreeHTML', 'TodoReport', 'database-differences-report', 'denominoviso', 'descendantspacetree', 'det_descendant_report_i', 'NumberOfAncestorsQuickview', 'NumberOfDescendantsQuickview', 'Anniversaries', 'ArchiveAssist', "Beta What's Next", 'Birthdays', 'ChatWithTree', 'Clock Gramplet', 'Collections Clipboard Gramplet', 'DNAMatches', 'DNASegmentMap', 'Data Entry Gramplet', 'Deep Connections Gramplet', 'Edit Image Exif Metadata', 'Form Gramplet', 'GetGOV Gramplet', 'GrampsChat', 'Grampy Script', 'Headline News', 'House Timeline', 'Import Gramplet', 'LastChangeGramplet', 'MediaBrowser', 'Note Gramplet', 'Participants', 'Photo Tagging', 'Place Coordinates', 'PlaceUpdate', 'Prerequisites Checker Gramplet', 'Python Gramplet', 'Related Relatives Gramplet', 'Search Gramplet', 'This Day in Family History', 'WebSearch', 'etree Gramplet', 'lxml Gramplet', 'postgresql', 'postgresqlenhanced', 'sharedpostgresql', 'MatrilinealProgenitrix', 'PatrilinealProgenitor', 'mtinheritance', 'mtinheritanceoffiltermatch', 'xchromancestors', 'xchromdescendants', 'yinheritance', 'yinheritanceoffiltermatch', 'AvatarGenerator', 'EventDescriptionEditor', 'FamilyTree DNA Import Tool', 'FixCoords', 'PlaceCompletion', 'SetAttribute', 'SetPrivacyTool', 'Topola', 'calculateestimateddates', 'climerge', 'downloadmedia', 'excity', 'gramps_web_sync', 'mediamerge', 'mediaverify', 'relationtab', 's3uploader', 'syncAssociations', 'thumbgen', 'typecleanup', 'im_sqlite', 'Export GEDCOM Extensions', 'Raw Export', 'ex_person_gexf', 'DE Web Connect Pack', 'FR Web Connect Pack', 'NL Web Connect Pack', 'RU Web Connect Pack', 'RestoreHist', 'SV Web Connect Pack', 'ThemesPrefs', 'UA Web Connect Pack', 'UK Web Connect Pack', 'US Web Connect Pack', 'libaccess', 'libwebconnect', 'GoogleEarth', 'HtreePedigreeView', 'QuiltView', 'TimelinePedigreeView', 'geoIDplaceCoordinateGramplet', 'geotimelines', 'lifelinechartancestorview', 'lifelinechartdescendantview']
;;recent-export-type=3
;;runcheck=0
spellcheck=1
;;startup=0
;;surname-guessing=0
translator-needed=0
use-tips=0
;;web-search-url='https://google.com/search?q=%(text)s'
;;welcome=100

[colors]
;;border-family=['#cccccc', '#252525']
;;border-family-divorced=['#ff7373', '#720b0b']
;;border-female-alive=['#861f69', '#261111']
;;border-female-dead=['#000000', '#000000']
;;border-male-alive=['#1f4986', '#171d26']
;;border-male-dead=['#000000', '#000000']
;;border-other-alive=['#2a5f16', '#26a269']
;;border-other-dead=['#000000', '#000000']
;;border-unknown-alive=['#8e5801', '#8e5801']
;;border-unknown-dead=['#000000', '#000000']
;;family=['#eeeeee', '#454545']
;;family-civil-union=['#eeeeee', '#454545']
;;family-divorced=['#ffdede', '#5c3636']
;;family-married=['#eeeeee', '#454545']
;;family-unknown=['#eeeeee', '#454545']
;;family-unmarried=['#eeeeee', '#454545']
;;female-alive=['#feccf0', '#62242D']
;;female-dead=['#feccf0', '#3a292b']
;;home-person=['#bbe68a', '#304918']
;;male-alive=['#b8cee6', '#1f344a']
;;male-dead=['#b8cee6', '#2d3039']
;;other-alive=['#94ef9e', '#285b27']
;;other-dead=['#94ef9e', '#062304']
;;scheme=0
;;unknown-alive=['#f3dbb6', '#75507B']
;;unknown-dead=['#f3dbb6', '#35103b']

[csv]
;;delimiter=','
;;dialect='excel'

[database]
autobackup=4
;;backend='sqlite'
;;backup-on-exit=1
backup-path='/Volumes/workplace/src/schierer/PAGI-WebServer/App-Schierer-HPFan/share/backups'
;;compress-backup=1
;;host=''
;;path='/Volumes/workplace/src/schierer/PAGI-WebServer/App-Schierer-HPFan/share/gramps/grampsdb'
;;port=''

[export]
;;proxy-order=[['privacy', 0], ['living', 0], ['person', 0], ['note', 0], ['reference', 0]]

[geography]
;;center-lat=0.0
;;center-lon=0.0
;;lock=0
;;map_service=1
;;path=''
;;personal-map=''
;;show_cross=0
;;use-keypad=1
;;zoom=0
;;zoom_when_center=12

[interface]
addonmanager-height=849
addonmanager-horiz-position=2322
addonmanager-vert-position=207
addonmanager-width=1093
child-ref-vert-position=417
citation-vert-position=389
dbmanager-height=370
dbmanager-horiz-position=4092
dbmanager-vert-position=335
;;dbmanager-width=780
;;dont-ask=0
editdate-height=360
editdate-horiz-position=1582
editdate-vert-position=628
editdate-width=688
event-ref-height=594
event-ref-vert-position=305
event-sel-vert-position=389
family-vert-position=448
;;filter=0
;;fullscreen=0
;;grampletbar-close=1
grampspreferences-height=897
grampspreferences-horiz-position=2066
grampspreferences-vert-position=52
grampspreferences-width=1136
hide-lds=1
;;ignore-gexiv2=0
;;ignore-osmgpsmap=0
;;ignore-pil=0
main-window-height=665
main-window-horiz-position=1467
main-window-vert-position=461
main-window-width=895
;;mapservice='OpenStreetMap'
;;open-with-default-viewer=0
;;pedview-layout=0
;;pedview-show-images=1
;;pedview-show-marriage=0
;;pedview-show-unknown-people=0
;;pedview-tree-direction=2
;;pedview-tree-size=5
;;person-height=550
;;person-horiz-position=1539
person-sel-vert-position=445
person-vert-position=283
person-width=891
;;place-name-height=100
;;place-name-width=450
;;sidebar-text=1
;;size-checked=0
source-sel-vert-position=389
source-sel-width=614
;;statusbar=1
;;surname-box-height=150
tipofday-height=665
tipofday-horiz-position=3726
tipofday-vert-position=559
tipofday-width=895
;;toolbar-addons=1
;;toolbar-clipboard=1
;;toolbar-on=1
;;toolbar-preference=1
;;toolbar-reports=1
;;toolbar-style=0
;;toolbar-tools=1
;;treemodel-cache-size=1000
updateaddons-horiz-position=1503
updateaddons-vert-position=554
;;view=1
;;view-categories=['Dashboard', 'People', 'Relationships', 'Families', 'Ancestry', 'Events', 'Places', 'Geography', 'Sources', 'Citations', 'Repositories', 'Media', 'Notes']

[paths]
;;quick-backup-directory='/Volumes/workplace/src/schierer/PAGI-WebServer/App-Schierer-HPFan/share'
;;quick-backup-filename='%(filename)s_%(year)d-%(month)02d-%(day)02d.%(extension)s'
;;recent-export-dir='/Volumes/workplace/src/schierer/PAGI-WebServer/App-Schierer-HPFan/share'
recent-file='/Volumes/workplace/src/schierer/PAGI-WebServer/App-Schierer-HPFan/share/gramps/grampsdb/potter_universe'
;;recent-import-dir='/Volumes/workplace/src/schierer/PAGI-WebServer/App-Schierer-HPFan/share'
;;report-directory='/Volumes/workplace/src/schierer/PAGI-WebServer/App-Schierer-HPFan/share'
;;website-cal-uri=''
;;website-cms-uri=''
;;website-directory='/Volumes/workplace/src/schierer/PAGI-WebServer/App-Schierer-HPFan/share'
;;website-extra-page-name=''
;;website-extra-page-uri=''

[plugin]
;;addonplugins=[]
;;hiddenplugins=[]

[preferences]
;;age-after-death=1
;;age-display-precision=1
;;age-rounded-year=1
;;calendar-format-input=0
;;calendar-format-report=0
;;cite-plugin='cite-legacy'
;;coord-format=0
;;cprefix='C%04d'
;;date-format=0
;;default-source=0
;;eprefix='E%04d'
;;family-relation-type=3
;;family-warn=0
;;february-29=0
;;fprefix='F%04d'
;;hide-ep-msg=0
;;invalid-date-format='<b>%s</b>'
;;iprefix='I%04d'
last-view='personview'
last-views=['dashboardview', 'personview', '', 'familyview', '', '', '', '', '', '', '', '', '']
;;name-format=1
;;no-given-text='[Missing Given Name]'
;;no-record-text='[Missing Record]'
;;no-surname-text='[Missing Surname]'
;;nprefix='N%04d'
;;online-maps=0
;;oprefix='O%04d'
;;paper-metric=0
;;paper-preference='Letter'
;;patronimic-surname=0
;;place-auto=1
;;place-format=0
;;pprefix='P%04d'
;;private-given-text='[Living]'
;;private-record-text='[Private Record]'
;;private-surname-text='[Living]'
;;quick-backup-include-mode=0
;;rprefix='R%04d'
;;sprefix='S%04d'
;;tag-on-import=0
;;tag-on-import-format='Imported %Y/%m/%d %H:%M:%S'
;;use-last-view=0

[researcher]
;;researcher-addr=''
;;researcher-city=''
;;researcher-country=''
researcher-email='luke@schierer.org'
;;researcher-locality=''
researcher-name='Luke Schierer'
;;researcher-phone=''
;;researcher-postal=''
;;researcher-state=''

[spacing]
childref_editor_citations=[2, 23.73589409722222, 13.563368055555555, 6.781684027777778, 12.20703125, 13.563368055555555, 5.425347222222222]
childref_editor_notes=[2, 6.781684027777778]
children=[16.954210069444446, 6.781684027777778, 6.781684027777778]
citation_editor_attributes=[2, 16.954210069444446]
citation_editor_notes=[2, 6.781684027777778]
citation_editor_references=[6.781684027777778, 5.086263020833333]
citations=[23.73589409722222, 10.172526041666666, 10.172526041666666, 13.563368055555555]
dbman=[16.954210069444446, 4.2724609375, 7.188585069444445]
eventref_editor_ref_attributes=[2, 2, 16.954210069444446]
eventref_editor_ref_citations=[2, 23.73589409722222, 13.563368055555555, 6.781684027777778, 12.20703125, 13.563368055555555, 5.425347222222222]
eventref_editor_ref_notes=[2, 6.781684027777778]
eventref_editor_references=[6.781684027777778, 5.086263020833333]
eventref_editor_shared_attributes=[2, 2, 16.954210069444446]
eventref_editor_shared_citations=[2, 23.73589409722222, 13.563368055555555, 6.781684027777778, 12.20703125, 13.563368055555555, 5.425347222222222]
eventref_editor_shared_notes=[2, 6.781684027777778]
events=[6.781684027777778, 10.172526041666666, 6.781684027777778, 6.781684027777778, 27.12673611111111, 13.563368055555555]
family_editor_attributes=[2, 2, 16.954210069444446]
family_editor_childrefs=[2, 2, 2, 4.069010416666667, 16.954210069444446, 5.086263020833333, 6.781684027777778, 6.781684027777778]
family_editor_citations=[2, 23.73589409722222, 13.563368055555555, 6.781684027777778, 12.20703125, 13.563368055555555, 5.425347222222222]
family_editor_events=[8.138020833333334, 16.276041666666668, 10.172526041666666, 16.276041666666668, 16.276041666666668, 2, 2, 5.425347222222222, 4.069010416666667]
family_editor_notes=[2, 6.781684027777778]
person_editor_addresses=[2, 2, 10.172526041666666, 15.2587890625, 6.781684027777778, 6.781684027777778, 6.781684027777778, 5.086263020833333, 5.086263020833333]
person_editor_associations=[2, 2, 16.954210069444446, 6.781684027777778]
person_editor_attributes=[2, 2, 16.954210069444446]
person_editor_citations=[2, 23.73589409722222, 13.563368055555555, 6.781684027777778, 12.20703125, 13.563368055555555, 5.425347222222222]
person_editor_events=[8.138020833333334, 16.276041666666668, 10.172526041666666, 16.276041666666668, 16.276041666666668, 2, 2, 5.425347222222222, 4.069010416666667]
person_editor_internet=[2, 6.781684027777778, 13.563368055555555]
;;person_editor_ldsord=[]
person_editor_names=[16.954210069444446, 2, 2, 6.781684027777778, 6.781684027777778]
person_editor_notes=[2, 6.781684027777778]
person_editor_references=[6.781684027777778, 5.086263020833333]
person_editor_surnames=[2, 2, 2, 2]
persontreeview=[16.954210069444446, 5.086263020833333, 5.086263020833333, 6.781684027777778]
selectcitation=[23.73589409722222, 6.781684027777778, 5.086263020833333]
selectevent=[6.781684027777778, 16.954210069444446, 10.172526041666666, 16.954210069444446, 10.172526041666666, 5.086263020833333]
selectperson=[16.954210069444446, 5.086263020833333, 5.086263020833333, 10.172526041666666, 10.172526041666666, 10.172526041666666, 10.172526041666666, 10.172526041666666]

[utf8]
;;baptism-symbol='~'
;;birth-symbol='*'
;;buried-symbol='[]'
;;cremated-symbol='⚱'
;;dead-symbol='✝'
;;death-symbol=2
;;divorce-symbol='o|o'
;;engaged-symbol='o'
;;in-use=0
;;killed-symbol='x'
;;marriage-symbol='oo'
;;partner-symbol='o-o'
;;selected-font=''

